### ISSUE TITLE
artboards duplicated after refreshing editor window

### ISSUE THREAD

**Issue by unikolas** [theprotein/protein-dynamics#71]
![image](https://cloud.githubusercontent.com/assets/906274/14505049/241bd2e4-01c0-11e6-9008-2041a3fad727.png)

**Comment by awinogradov** [comment]
I couldn't repeat it. @unikolas how you found this problem?:)

**Comment by unikolas** [comment]
@awinogradov press cmd+R in editor. Maybe Reexport in Sketch

**Comment by awinogradov** [comment]
I found the problem. When we setup screens we push all screens to the array. On screens update, we push updated screens too ;( Layers doesn't update because reducers doesn't know about new information.
