### ISSUE TITLE
symbol's content exported as artboard

### ISSUE THREAD

**Issue by unikolas** [theprotein/protein-dynamics#73]
I see the symbol's content as an artboard
![image](https://cloud.githubusercontent.com/assets/906274/14505693/f069aef0-01c2-11e6-83ae-ce41dd9b8897.png)

And Rect "mmm" from symbol as a group in layer tree
![image](https://cloud.githubusercontent.com/assets/906274/14505716/09784b9a-01c3-11e6-9458-4db704e9abf9.png)

**Comment by unikolas** [comment]
Pretty cool sketch file example. With symbol and non symbol group for comparing
[Symbol test.zip](https://github.com/theprotein/protein-dynamics/files/222296/Symbol.test.zip)

**Comment by awinogradov** [comment]
It's not a bug. We can solve this problem in the plugin. You mustn't export Symbols page! I made issue https://github.com/theprotein/protein-dynamics-plugin/issues/3  to prevent this action in Sketch.
