### ISSUE TITLE
fix for overrounded buttons

### ISSUE THREAD

**Issue by unikolas** [theprotein/protein-dynamics#83]
@awinogradov  if Radius of imported element greater than smallest dimension of this element you should set it to half of this dimension

Example:

Source
![image](https://cloud.githubusercontent.com/assets/906274/14589303/5ab6594e-04e7-11e6-89df-3da32d518a48.png)

Wrong — Current import result
![image](https://cloud.githubusercontent.com/assets/906274/14589362/a5c90174-04e8-11e6-8c99-6b0f1b0fcd48.png)

Right
![image](https://cloud.githubusercontent.com/assets/906274/14589368/ba923756-04e8-11e6-9284-b68b6644c132.png)

**Comment by awinogradov** [comment]
🔥 👊
