### ISSUE TITLE
fix border 'inside' for objects

### ISSUE THREAD

**Issue by unikolas** [theprotein/protein-dynamics#88]
SVG uses only 'center' position for stroke.
In sketch designers usually use 'inside' position for buttons and icons. To make visual consistency for imported designs we have to fix size and border-radius.

@awinogradov no needs to discover a solution. Drink whiskey and use this simple rules: 
newWidth = width - borderWidth
newHeight = height - borderWidth
newBorderRadius = borderRadius - borderWidth/2

1 — source.
2 — example with 'center' position and fixed size.
3 — example with fixed position, size, and borderRadius.
![image](https://cloud.githubusercontent.com/assets/906274/14652820/b7d093cc-067e-11e6-9615-87810a2562c1.png)

**Comment by unikolas** [comment]
One problem. Hello 1px stroke
![image](https://cloud.githubusercontent.com/assets/906274/14653940/12b99af4-0684-11e6-9f41-58a6be71ce55.png)

**Comment by awinogradov** [comment]
@unikolas what designer should choose in Sketch for right work in SVG?

**Comment by unikolas** [comment]
@awinogradov 
Border position. But nobody uses Center. It's fucking pain.
![image](https://cloud.githubusercontent.com/assets/906274/15018258/877752f2-1221-11e6-8c69-1a89e83d28f8.png)

**Comment by unikolas** [comment]
@awinogradov default value in sketch is Inside for example. There is no reason to use Center. Designers who use it are sick

**Comment by zxqfox** [comment]
I'd say "Center" is for young painters who can't handle borders right. 👍 to @unikolas

**Comment by zxqfox** [comment]
Inside:
```
<defs>
    <path id="ld" d="M256,0 L0,512 L384,512 L128,1024 L1024,384 L640,384 L896,0 L256,0 Z"/>
    <clipPath id="clip">
        <use xlink:href="#ld"/>
    </clipPath>
</defs>
<g>
    <use xlink:href="#ld" stroke="#0081C6" stroke-width="160" fill="#00D2B8" clip-path="url(#clip)"/>
</g>
```

**Comment by awinogradov** [comment]
@zxqfox 🔥

**Comment by unikolas** [comment]
![image](https://cloud.githubusercontent.com/assets/906274/15057413/524941b8-131f-11e6-90fd-cc63214cc80f.png)

fixed by Sketch. They use mask now.
